export interface MysteryClueDefinition {
  text: string;
  category: string;
  genre: 'noir' | 'thriller' | 'horror' | 'romance' | 'scifi' | 'adventure' | 'all';
  difficulty: 'EASY' | 'MEDIUM' | 'HARD';
  visualElements: string[];
  acceptedConcepts: string[];
  hint: string;
}

export const MASTER_MYSTERY_CLUES: MysteryClueDefinition[] = [
  {
    text: 'Bloody Footprint',
    category: 'Forensic Evidence',
    genre: 'noir',
    difficulty: 'EASY',
    visualElements: ['red shoe print', 'floor tiles', 'blood spatter'],
    acceptedConcepts: ['bloody footprint', 'shoe print', 'boot print', 'footprint', 'blood print'],
    hint: 'Evidence left on the crime scene floor.',
  },
  {
    text: 'Broken Pocket Watch',
    category: 'Personal Item',
    genre: 'noir',
    difficulty: 'EASY',
    visualElements: ['cracked glass face', 'roman numerals', 'gold chain', 'stopped hands'],
    acceptedConcepts: ['pocket watch', 'broken watch', 'gold watch', 'broken pocket watch', 'stopwatch'],
    hint: 'A timepiece frozen at the exact time of the incident.',
  },
  {
    text: 'Cyanide Vial',
    category: 'Poison & Chemistry',
    genre: 'noir',
    difficulty: 'MEDIUM',
    visualElements: ['small glass bottle', 'skull label', 'dropper', 'green liquid'],
    acceptedConcepts: ['cyanide', 'poison bottle', 'vial', 'toxic bottle', 'poison vial', 'chemical'],
    hint: 'A tiny bottle containing lethal liquid.',
  },
  {
    text: 'Torn Train Ticket',
    category: 'Travel Evidence',
    genre: 'thriller',
    difficulty: 'EASY',
    visualElements: ['ripped paper', 'stamped time', 'barcode or punch hole', 'train logo'],
    acceptedConcepts: ['train ticket', 'torn ticket', 'ticket', 'stub', 'rail ticket'],
    hint: 'Proof that a passenger boarded the midnight express.',
  },
  {
    text: 'Fingerprint on Glass',
    category: 'Forensic Evidence',
    genre: 'noir',
    difficulty: 'EASY',
    visualElements: ['spiral fingerprint ridges', 'magnifying glass', 'wine glass or window'],
    acceptedConcepts: ['fingerprint', 'glass fingerprint', 'thumbprint', 'print on glass'],
    hint: 'A smudge left on a drinking cup or window pane.',
  },
  {
    text: 'Burnt Love Letter',
    category: 'Personal Document',
    genre: 'romance',
    difficulty: 'MEDIUM',
    visualElements: ['singed paper edges', 'cursive writing', 'envelope', 'ashes and flame'],
    acceptedConcepts: ['burnt letter', 'love letter', 'letter', 'envelope', 'burned note', 'secret message'],
    hint: 'A charred note containing forbidden confessions.',
  },
  {
    text: 'Forged Passport',
    category: 'Identity & Transit',
    genre: 'thriller',
    difficulty: 'MEDIUM',
    visualElements: ['passport booklet', 'tampered photo', 'fake visa stamp', 'embossed crest'],
    acceptedConcepts: ['fake passport', 'forged passport', 'passport', 'fake id', 'alias document'],
    hint: 'Travel credentials bearing a false identity.',
  },
  {
    text: 'Brass Vault Key',
    category: 'Security & Access',
    genre: 'noir',
    difficulty: 'EASY',
    visualElements: ['heavy antique key', 'brass metal', 'teeth grooves', 'keychain tag'],
    acceptedConcepts: ['vault key', 'brass key', 'skeleton key', 'master key', 'key'],
    hint: 'An ornate tool that unlocks the subterranean safe.',
  },
  {
    text: 'Shattered Wine Glass',
    category: 'Crime Scene Evidence',
    genre: 'noir',
    difficulty: 'EASY',
    visualElements: ['broken stemware', 'spilled red liquid', 'sharp glass shards'],
    acceptedConcepts: ['broken glass', 'wine glass', 'shattered glass', 'spilled wine', 'champagne flute'],
    hint: 'Drinkware smashed during a sudden banquet confrontation.',
  },
  {
    text: 'Black Leather Gloves',
    category: 'Disguise & Concealment',
    genre: 'noir',
    difficulty: 'EASY',
    visualElements: ['pair of dark gloves', 'stitched fingers', 'dropped near doorway'],
    acceptedConcepts: ['leather gloves', 'gloves', 'black gloves', 'burglar gloves'],
    hint: 'Worn to leave no fingerprints behind.',
  },
  {
    text: 'Smoking Revolver',
    category: 'Weapon & Ballistics',
    genre: 'noir',
    difficulty: 'EASY',
    visualElements: ['gun barrel', 'revolver cylinder', 'wisp of gray smoke', 'trigger'],
    acceptedConcepts: ['revolver', 'gun', 'pistol', 'smoking gun', 'handgun'],
    hint: 'A firearm that was discharged just seconds ago.',
  },
  {
    text: 'Hidden Microfilm',
    category: 'Espionage',
    genre: 'thriller',
    difficulty: 'HARD',
    visualElements: ['tiny transparent film strip', 'miniature frames', 'magnifier'],
    acceptedConcepts: ['microfilm', 'secret film', 'spy film', 'film strip', 'mini film'],
    hint: 'A microscopic strip storing state secrets.',
  },
  {
    text: 'Red Lipstick on Collar',
    category: 'Romantic Suspicion',
    genre: 'romance',
    difficulty: 'MEDIUM',
    visualElements: ['shirt collar', 'red lip stain', 'buttoned suit'],
    acceptedConcepts: ['lipstick on collar', 'lipstick stain', 'collar mark', 'kiss mark'],
    hint: 'Tell-tale crimson mark on an unfaithful lover’s shirt.',
  },
  {
    text: 'Security Camera Wire Cut',
    category: 'Sabotage',
    genre: 'thriller',
    difficulty: 'MEDIUM',
    visualElements: ['dome camera', 'severed cables', 'sparking copper wire'],
    acceptedConcepts: ['camera wire cut', 'cut wire', 'cut cable', 'severed wire', 'disabled camera'],
    hint: 'Intentionally snipped to blind the museum guards.',
  },
  {
    text: 'Diamond in Briefcase',
    category: 'Valuable Property',
    genre: 'noir',
    difficulty: 'EASY',
    visualElements: ['open leather briefcase', 'glowing gemstone', 'foam padding', 'currency stacks'],
    acceptedConcepts: ['diamond in briefcase', 'diamond briefcase', 'briefcase diamond', 'briefcase gem'],
    hint: 'A gleaming jewel concealed inside courier luggage.',
  },
  {
    text: 'Vintage Film Reel',
    category: 'Secret Record',
    genre: 'noir',
    difficulty: 'MEDIUM',
    visualElements: ['circular spool', 'celluloid film strip', 'projector light beam'],
    acceptedConcepts: ['film reel', 'movie reel', 'vintage reel', 'projector reel', 'film roll'],
    hint: 'Old footage capturing the truth behind the disappearance.',
  },
  {
    text: 'Blood on Chandelier',
    category: 'Crime Scene Evidence',
    genre: 'horror',
    difficulty: 'MEDIUM',
    visualElements: ['crystal chandelier', 'dripping crimson drop', 'hanging light'],
    acceptedConcepts: ['blood on chandelier', 'chandelier blood', 'dripping chandelier'],
    hint: 'Evidence found high above the ballroom floor.',
  },
  {
    text: 'Silver Lockpick',
    category: 'Burglary Tool',
    genre: 'noir',
    difficulty: 'EASY',
    visualElements: ['slender metal tension wrench', 'pick tool inserted in keyhole'],
    acceptedConcepts: ['lockpick', 'lock pick', 'tension wrench', 'lockpick tool'],
    hint: 'A burglar’s slender needle for cracking locked doors.',
  },
  {
    text: 'Encrypted Diary',
    category: 'Personal Document',
    genre: 'thriller',
    difficulty: 'MEDIUM',
    visualElements: ['leather-bound journal', 'brass padlock', 'ciphers and symbols'],
    acceptedConcepts: ['secret diary', 'locked diary', 'encrypted diary', 'journal', 'code book'],
    hint: 'A notebook filled with scrambled codes and secrets.',
  },
  {
    text: 'Torn Photograph',
    category: 'Personal Memory',
    genre: 'romance',
    difficulty: 'EASY',
    visualElements: ['photograph ripped in half', 'couple separated by jagged edge'],
    acceptedConcepts: ['torn photo', 'ripped photo', 'torn photograph', 'half photo', 'old picture'],
    hint: 'A picture of two people deliberately severed.',
  },
  {
    text: 'Disguised Waiter',
    category: 'Undercover Suspect',
    genre: 'noir',
    difficulty: 'MEDIUM',
    visualElements: ['bowtie and vest', 'silver tray', 'listening ear', 'concealed wire'],
    acceptedConcepts: ['waiter', 'disguised waiter', 'spy waiter', 'fake waiter', 'catering spy'],
    hint: 'An operative posing as dinner staff at the gala.',
  },
  {
    text: 'Masked Intruder',
    category: 'Suspect',
    genre: 'thriller',
    difficulty: 'EASY',
    visualElements: ['black balaclava or porcelain mask', 'dark hoodie', 'glowing eyes'],
    acceptedConcepts: ['masked intruder', 'burglar', 'intruder', 'thief', 'masked thief'],
    hint: 'A shadowy figure who slipped past perimeter lasers.',
  },
  {
    text: 'Security Guard Sleeping',
    category: 'Inside Job',
    genre: 'noir',
    difficulty: 'EASY',
    visualElements: ['uniform with badge', 'slumped at desk', 'coffee mug tipped', 'sleeping cap'],
    acceptedConcepts: ['sleeping guard', 'security guard sleeping', 'drugged guard', 'guard sleeping'],
    hint: 'The night watchman knocked out by poisoned coffee.',
  },
  {
    text: 'Ticking Grandfather Clock',
    category: 'Time & Setting',
    genre: 'horror',
    difficulty: 'EASY',
    visualElements: ['tall wooden clock', 'swinging brass pendulum', 'clock face at midnight'],
    acceptedConcepts: ['grandfather clock', 'tall clock', 'antique clock', 'clock pendulum'],
    hint: 'A vintage standing clock chiming twelve in the hallway.',
  },
  {
    text: 'Antique Music Box',
    category: 'Haunted Artifact',
    genre: 'horror',
    difficulty: 'MEDIUM',
    visualElements: ['wooden box with winding key', 'spinning ballerina', 'musical notes'],
    acceptedConcepts: ['music box', 'antique music box', 'ballerina box', 'winding box'],
    hint: 'A wind-up box that plays an eerie melody by itself.',
  },
  {
    text: 'Red Sports Getaway Car',
    category: 'Escape Vehicle',
    genre: 'thriller',
    difficulty: 'EASY',
    visualElements: ['sleek red convertible', 'spinning wheels', 'smoke trails', 'exhaust flame'],
    acceptedConcepts: ['getaway car', 'sports car', 'red car', 'escape car', 'speeding car'],
    hint: 'The vehicle that sped away from the back alley.',
  },
  {
    text: 'Secret Bookshelf Door',
    category: 'Hidden Passage',
    genre: 'noir',
    difficulty: 'MEDIUM',
    visualElements: ['wooden bookcase swinging outward', 'dark tunnel revealed', 'rows of books'],
    acceptedConcepts: ['secret door', 'bookshelf door', 'hidden passage', 'secret room', 'bookcase'],
    hint: 'A wall of books that swings open into a hidden chamber.',
  },
  {
    text: 'Golden Egyptian Scarab',
    category: 'Ancient Relic',
    genre: 'adventure',
    difficulty: 'EASY',
    visualElements: ['gold beetle amulet', 'hieroglyphic carvings', 'emerald wings'],
    acceptedConcepts: ['scarab', 'golden scarab', 'egyptian amulet', 'gold beetle', 'scarab beetle'],
    hint: 'An ancient Egyptian talisman stolen from the Pharaoh gallery.',
  },
  {
    text: 'Crown Jewels in Velvet Box',
    category: 'Royal Valuables',
    genre: 'noir',
    difficulty: 'EASY',
    visualElements: ['royal tiara with rubies and sapphires', 'plush red velvet case', 'silk cushion'],
    acceptedConcepts: ['crown jewels', 'royal crown', 'tiara', 'velvet box', 'jeweled crown'],
    hint: 'Regal headwear studded with rubies and diamonds.',
  },
];

export class ClientInfiniteClueEngine {
  public static getRandomClues(count: number, excludedWords: string[] = []): MysteryClueDefinition[] {
    const excludedNorm = new Set(excludedWords.map((w) => w.toLowerCase().trim()));
    const eligible = MASTER_MYSTERY_CLUES.filter((c) => !excludedNorm.has(c.text.toLowerCase().trim()));
    const pool = eligible.length >= count ? eligible : MASTER_MYSTERY_CLUES;
    const shuffled = [...pool].sort(() => Math.random() - 0.5);
    return shuffled.slice(0, count);
  }
}
